language: python

services:
  - docker

env:
  global:
    - IMAGE_NAME=playground

stages:
  - build
  - test

install:
  - echo 'Nothing to install right now...'

before_script:
  # Confirm presence of docler
  - docker info

jobs:
  include:
    - stage: build
      name: Build
      script:
        # Build playground docker-image
        - docker build -t $DOCKER_USER/$IMAGE_NAME -f local/docker/Dockerfile .
        # List docker images
        - docker images
    - stage: test
      name: Docker Image
      script:
        # Run playground docker-image
        - docker run -d -u $(id -u):$(id -g) -v //var/run/docker.sock://var/run/docker.sock:rw -p 8001-8080:8001-8080 adisakshya/playground
        # Try reaching code-server
        - curl localhost:8080/login
        # List all docker containers
        - docker ps -a
    - stage: test
      name: Install Script - Debian
      script:
        # Run debian install script
        - bash $(pwd)/local/shell/debian.sh
    - stage: test
      name: Install Script - Amazon Linux
      script:
        # Run amazon-linux install script in docker-container
        - docker run --rm -v $(pwd)/local/shell/amazon-linux.sh:/playground/amazon-linux.sh amazonlinux bash /playground/amazon-linux.sh
