language: node_js
node_js:
    - "12"

services:
  - docker

env:
  global:
    - IMAGE_NAME=$DOCKER_USER/playground
      
before_script:
  # Get version information
  - VERSION="$(awk '$2 == "PLAYGROUND_VERSION" { print $3; exit }' src/Dockerfile)"
  # Confirm presence of docler
  - docker info
  # Pull latest playground docker image
  - docker pull "$IMAGE_NAME" || true

install:
  - echo "install nothing!"

stages:
  - name: build
  - name: deploy
    if: branch = master AND type = push AND fork = false

docker_login:
    before_script:
      - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"

jobs:
  include:
    # Build playground docker image
    - stage: build
      script:
        - docker build -t playground -f src/Dockerfile --cache-from $IMAGE_NAME .
        - docker images
    # Build and push playground docker image to dockerhub
    - stage: deploy
      before_script: *docker_login
      script:
        - docker build -t playground -f src/Dockerfile --cache-from $IMAGE_NAME .
        - docker images
        - docker tag playground $IMAGE_NAME:latest
        - docker tag playground $IMAGE_NAME:$VERSION
        - docker push $IMAGE_NAME:latest
        - docker push $IMAGE_NAME:$VERSION

# Don't notify me when things fail
notifications:
  email: false
