language: node_js
node_js:
    - "12"

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - IMAGE_NAME=$DOCKER_USER/playground
      
before_script:
  # Get version information
  - VERSION="$(awk '$2 == "PLAYGROUND_VERSION" { print $3; exit }' src/Dockerfile)"
  # Confirm presence of docler
  - docker info
  # Pull latest playground docker image
  - docker pull "$IMAGE_NAME" || true
  # Install docker-compose
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - echo "install nothing!"

# Build playground and proxy
script:
  - docker build -t $IMAGE_NAME -f src/Dockerfile --cache-from $IMAGE_NAME .
  - docker-compose -f src/reverse-proxy/docker-compose.yml build

# List all docker images
after_script:
  - docker images

# Push to playground docker image to dockerhub
after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - docker tag $IMAGE_NAME $IMAGE_NAME:latest
  - docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION
  - docker push $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:$VERSION

# Don't notify me when things fail
notifications:
  email: false
